ESX.RegisterUsableItem("carokit", function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    TriggerClientEvent("null:kit:mecano:repair", source)
    xPlayer.removeInventoryItem("carotkit", 1)
end)

ESX.RegisterUsableItem("cleankit", function(source)
    local xPlayer = ESX.GetPlayerFromId(source)
    TriggerClientEvent("null:kit:mecano:clean", source)
    xPlayer.removeInventoryItem("cleankit", 1)
end)