RegisterNetEvent("null:staff:changeNTable", function(key, value)
    nTable[key] = value
end)

nTable = {
    source = {},
    reportList = {},
    reportCountList = {},
    staffList = {},
    staffListOffline = {},
    topStaff = {},
    cashListEconomieLoad = false,
    zoneShow = false,
    illegalBlips = false,
    infiniteMaxWeight = true,
    cashListEconomie = {},
    searchPlayerId = {},
    searchPlayerIdUnique = {},
    group = {},
    items = {},
    weapons = {},
    Players = {},
    TypeInfo = 5,
    NbrTotalPlayers = 0,
    tableUsers = {},
    playerByIdU = {},
    blTableUsers= {
        ["status"] = true,
        ["skin"] = true,
        ["permission_level"] = true,
        ["eval_staff"] = true,
        ["tattoo"] = true,
        ["ata"] = true,
        ["apps"] = true,
        ["widget"] = true,
        ["bt"] = true,
        ["charinfo"] = true,
        ["metadata"] = true,
        ["cryptocurrency"] = true,
        ["cryptocurrencytransfers"] = true,
    },
    onlyALLWeapon = 1,
    onlyALLItems = 1,

    IndexTypeGangBuilder = 1,
    TypeGangBuilder = {"Gang","Organisation","Cartel"},

    CreateZoneGf = {},

    StreamerConnected = {},
    StreamerList = {},

    AllAta = {},

    EventCamionProps = {},
    PosCamionBlinder = nil,

    AllPlayers = {},
    SelectedAllPlayer = {},
    SelectedIsCo = false,

    EvalStaffHisto = {},

    PagePlayers = {},
    NbrPagePlayer = 0,
    PageList = {},
    ActualPage = 1,

    SelectedPlayers = {},

    takenReporttt = 0,

    createdItem = {},

    historyDecoReco = {},

    DemandeBraquage = {},
    BraquageBrinks = {},
    DemandeBraquageAttente = {},

    objectFilterUniqueId = false,
    blackoutStatus = true,
    ascenseur = AscenseurList or {},
    SelectedElevator = nil,
    elevatorCreate = {
        positions = {}
    },

    garageList = {},
    selectedGarage = {},

    territories = {},
    territoriesShop = {},
    
    CreateZoneSafe = {
        points = {}
    },
    ZoneSafe = {},
    SelectedSafeZone = {},
    FiltreZoneSafe = nil,

    Cellule = {},
    
    tirAppels = false,
    streamer = false,

    garageblip = false,
    gangblip = false,

    Entreprises = {},
    Entreprises2 = {
        ["Mécano"] = {},
        ["Bar"] = {},
        ["Ambulance"] = {},
        ["Police"] = {},
        ["Farm"] = {},
        ["Restaurant"] = {},
    },
    SelectedEntreprise = nil,
    
    OpenAllEntreprisesCollap = false,
    ShowCreateEntreprise = false,

    TeleportEntrepriseIndex = 1,
    TeleportEntrepriseList = {},

    fonda = false,

    FiltreTenue = nil,
    FiltreWeapon = nil,
    FiltreAcc = nil,
    FiltreItem = nil,

    banList = {},
    banList2 = {},
    banID = "",
    banNAME = "",
    bansourceNAME = "",
    banLICENSE= "",
    banRAISON = "",
    banNOTE = "",

    economieTotal = 0,
    economieTotalCash = 0,
    economieTotalBlack = 0,
    economieTotalBank = 0,

    weaponNAME = "",
    weaponHASH = "",

    injailtime = 0,
    injail = false,

    jailList = {},
    jailSTAFFNAME = "",
    jailLICENSE= "",
    jailRAISON = "",
    jailTIME = 0,

    tenueList = {},
    tenueNAME = "",
    tenueSKIN = {},
    tenueID = 0,

    accsList = {},
    accsNAME = "",
    accsTYPE = "",
    accsSKIN = {},
    accsID = 0,

    vehList = {},
    vehOwner = "",
    vehPlate = "",
    vehVehicle = {},
    vehModel = "",
    vehType = "",
    vehState = 0,
    vehLabel = "",
    vehBoutique = 0,

    markersBlips = false,
    markerJob = nil,
    markerAction = nil,
    markername = nil,
    markernamenoespace = nil,
    markersvector3 = nil,
    markersBlipsCouleur = "",
    markersBlipsSprit = "",
    markersBlipsName = "",

    
    actionSelected = {},
    actionSelectedLabel = "",
    hasSelected = false,
    SelectedAction = "",

    inventory = {},
    reportCount = 0,
    reportTotalCount = 0,
    reportNoTraiter = 0,
    hidetaken = false,
    hidestaff = false,
    hidevhBoutique = false,
    hidevhnoBoutique = false,
    hidejoueurs = false,
    loadout = {},
    idunique = 0,
    sanction = {},
    sanction2 = {},
    historiqueidu = {},
    packidu = {},
    allWeapons = {},
    allJobs = {},
    allGrades = {},
    search = {},
    vehicleSell = {},
    name = "",
    groupstaff = "",
    job = {},
    job2 = {},
    cash = "",
    bank = "",
    black = "",
    identifier = "",
    ranks = "",
    filterArray = { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" },
    refreshPlayerList = {"Recherche ID", "Refresh la liste"},
    rechercheIndex = {"ID", "ID Uniques~s~", "Nom"},
    giveType = {"Argent liquide", "Argent en banque", "Argent sale", "PPA", "Permis de conduire"},
    histoSanction = {"Jail", "Warn", "Kick", "Ban"},
    wipeList = {"Inventaire", "Armes", "Véhicules", "Général"},
    weaponList = {"Blanche", "Pistolet", "Fusil d'assault", "Mitraillette", "Arme lourde"},
    jobFilter = {"Job 1", "Job 2"},
    vehSpeed = {"Désactiver", "x16", "x32", "x64", "x128", "x256", "x1024"},
    tenueListe = {"Equiper", "Retirer"},
    annonceList = {"Annonce", "Annonce Staff", "Reboot"},
    vehColor = {"Rouge", "Bleu", "Noir", "Orange", "Blanc"},
    ActionDirt = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'}, 
    ListeActionDirt = 1,
    searchId = false,
    searchIdUnique = false,
    searchIdUniqueResult = nil,
    playerAsBeenSearchIdUnique = "",
    searchiduGroup = nil,
    searchiduJob = "",
    searchidujob2 = "",


    searchVhPlate = false,
    searchFindVhPlate = false,
    searchVhVehicle = "",
    searchVhBoutique = "",
    searchVhFouriere = "",
    searchVhPlate2 = "",
    searchVhOwner = "",
    searchVhModel = "",
    searchVhLabel = "",


    estmort = false,
    loadoutIDU = {},
    staffmode = false,
    sourcereport = nil,
    spectate = false,
    staffmodeSTAFF = false,
    nbrReportSTAFF = 0,
    objets = false,
    staffTenu = false,
    filtreOk = false,
    adminHudOK = false,
    sanctionOk = false,
    isPeds = false,
    banTimeOk = false,
    identifierStaff = nil,
    banReasonOk = false,
    jailTimeOk = false,
    jailReasonOk = false,
    jailFinish = false,
    superjump = false,
    noragdol = false,
    delgun = false,
    spawncarr = false,
    supersprint = false,
    playerFreeze = false,
    vehicleFreeze = false,
    hideTakenReports = false,
    InSearch = false,
    vhInvisible = false,
    gamerTag = false,
    gamerTag2 = false,
    gamerTag3 = false,
    gamerTagAdvanced = false,
    noclip = false,
    isSpectateMod = false,
    blipActive = false,
    invincible = false,
    invisible = false,
    adminHud = false,
    songreport = true,
    notifreport = true,
    in_spectate = false,
    setCoord = false,
    takenby = "Personne",
    taken = false,
    List = 1,
    List2 = 1,
    List3 = 1,
    List4 = 1,
    List5 = 1,
    List6 = 1,
    List7 = 1,
    List8 = 1,
    List9 = 1,
    List10 = 1,
    List11 = 1,
    List12 = 1,
    List13 = 1,
    List14 = 1,
    IndexColor = {1,1,1},

    PlyInFarm = {},

    CreateDrugs = {
        Laboratory = {
            active = false,
            list = {
                ['weed_laboratory'] = {
                    name = 'weed_laboratory',
                    label = 'Laboratoire de Weed',
                    active = false,
                    exit = vector3(1066.15, -3183.38, -40.15),
                    exitHeading = 90.0,
                    interiorAtCoords = vector3(1051.491, -3196.536, -39.14842),
                    management = vector3(1044.605, -3194.886, -38.15789),
                    ipls = true,
                    iplsList = {
                        'weed_drying',
                        'weed_production',
                        'weed_set_up',
                        'weed_standard_equip',
                        'weed_upgrade_equip',
                        'weed_growtha_stage1',
                        'weed_growtha_stage2',
                        'weed_growtha_stage3',
                        'weed_growthb_stage1',
                        'weed_growthb_stage2',
                        'weed_growthb_stage3',
                        'weed_growthc_stage1',
                        'weed_growthc_stage2',
                        'weed_growthc_stage3',
                        'weed_growthd_stage1',
                        'weed_growthd_stage2',
                        'weed_growthd_stage3',
                        'weed_growthe_stage1',
                        'weed_growthe_stage2',
                        'weed_growthe_stage3',
                        'weed_growthf_stage1',
                        'weed_growthf_stage2',
                        'weed_growthf_stage3',
                        'weed_growthg_stage1',
                        'weed_growthg_stage2',
                        'weed_growthg_stage3',
                        'weed_growthh_stage1',
                        'weed_growthh_stage2',
                        'weed_growthh_stage3',
                        'weed_growthi_stage1',
                        'weed_growthi_stage2',
                        'weed_growthi_stage3',
                        'weed_hosea',
                        'weed_hoseb',
                        'weed_hosec',
                        'weed_hosed',
                        'weed_hosee',
                        'weed_hosef',
                        'weed_hoseg',
                        'weed_hoseh',
                        'weed_hosei',
                        'light_growtha_stage23_standard',
                        'light_growthb_stage23_standard',
                        'light_growthc_stage23_standard',
                        'light_growthd_stage23_standard',
                        'light_growthe_stage23_standard',
                        'light_growthf_stage23_standard',
                        'light_growthg_stage23_standard',
                        'light_growthh_stage23_standard',
                        'light_growthi_stage23_standard',
                        'light_growtha_stage23_upgrade',
                        'light_growthb_stage23_upgrade',
                        'light_growthc_stage23_upgrade',
                        'light_growthc_stage23_upgrade',
                        'light_growthd_stage23_upgrade',
                        'light_growthe_stage23_upgrade',
                        'light_growthf_stage23_upgrade',
                        'light_growthg_stage23_upgrade',
                        'light_growthh_stage23_upgrade',
                        'light_growthi_stage23_upgrade',
                        'weed_low_security',
                        'weed_security_upgrade',
                        'weed_chairs'
                    },
                },
                --[[['coke_laboratory'] = {
                    name = 'coke_laboratory',
                    description = "Uniquement un traitement dans le laboratoire",
                    label = 'Laboratoire de Coke',
                    active = false,
                    exit = vector3(1088.714, -3187.605, -38.99348-0.98),
                    exitHeading = 185.81629943847656,
                    management = vector3(1087.142, -3194.295, -38.99342),
                    interiorAtCoords = vector3(1093.6, -3196.6, -38.99841),
                    ipls = true,
                    iplsList = {},
                },]]
                ['meth_laboratory'] = {
                    name = 'meth_laboratory',
                    label = 'Laboratoire de Meth',
                    active = false,
                    exit = vector3(996.8676, -3200.702, -36.39373-0.98),
                    exitHeading = 259.3778991699219,
                    management = vector3(1002.126, -3194.958, -38.99319),
                    interiorAtCoords = vector3(1009.5, -3196.6, -38.99682),
                    ipls = false,

                },
            },
            Index = 1
        }
    },
    advancedparaanim = false,
    NullLabo = {},
    SelectedDrugs = {},
    SelectedDrugsCategorie = 'recolte',

    WeaponLabel = "",
    WeaponName = "",
    WeaponIsOnline = false,
    WeaponComponents = nil,
    WeaponAmmo = 0
}

exports('getAdminTable', function()
    return nTable
end)
